import {
  analyzePrompt,
  providerFromConfig,
  type AIProvider,
  type AIProviderConfig,
  type Analysis,
} from './provider.js';
import { detectDestructiveOps } from './validate.js';
import { validatePlan, type ExistingState, type PlanValidation } from './validate.js';
import { buildMigration, type Migration } from './migrate.js';
import { diffPlan, estimateResources, type ChangeLine } from './preview.js';
import type { PlanStore, PermissionLevel, StoredPlan } from './approvals.js';
import type { AIAuditLog, AIUsageTracker } from './audit.js';
import { executeTool, type ToolAdapters } from './tools.js';
import { scanGeneratedCode, type ScanResult } from './scanner.js';
import type { AIPlan, DestructiveOp } from './plan.js';

/**
 * AIBackendBuilder — generation is strictly separated from execution.
 * The builder produces a validated, diffed, approved plan; only the API
 * layer's apply path (with project-bound tool adapters) touches
 * infrastructure, step by step with stop-on-failure semantics.
 */

export interface BuilderOptions {
  provider: AIProvider;
  plans: PlanStore;
  audit: AIAuditLog;
  usage: AIUsageTracker;
}

export interface ApplyOutcome {
  plan: StoredPlan;
  migration: Migration | null;
  steps: { step: string; ok: boolean; detail: string }[];
  ok: boolean;
  rolledBack: boolean;
  error: string | null;
}

/** Vetted handler scaffold for trigger-based functions (scanned before deploy). */
export function scaffoldFunctionSource(
  name: string,
  purpose: string,
  trigger: string,
  table?: string,
): string {
  const safePurpose = purpose.replace(/\*\//g, '* /').slice(0, 500);
  return [
    '/**',
    ` * ${safePurpose}`,
    ` * Generated by CloudNivo AI Builder as function "${name}" (${trigger}${table ? ` on ${table}` : ''}).`,
    ' * Runs isolated: no require/process/fetch — use req + cloudnivo SDK only.',
    ' */',
    'module.exports.handler = async (req) => {',
    '  // TODO: implement with your provider call (email/push/webhook).',
    "  console.log('ai-function invoked', req.path);",
    '  return { status: 200, body: { ok: true, function: req.auth ? undefined : undefined } };',
    '};',
    '',
  ].join('\n');
}

export class AIBackendBuilder {
  constructor(private readonly opts: BuilderOptions) {}

  analyzeRequest(prompt: string): Analysis {
    return analyzePrompt(prompt);
  }

  generateArchitecture(prompt: string): { intents: string[] } {
    return { intents: analyzePrompt(prompt).intents };
  }

  async generateDatabaseSchema(
    prompt: string,
    ctx: Record<string, unknown>,
  ): Promise<AIPlan['database']> {
    const { plan } = await this.opts.provider.generate(prompt, ctx);
    return plan.database;
  }

  async generateAPIDesign(
    prompt: string,
    ctx: Record<string, unknown>,
  ): Promise<{ endpoints: { method: string; path: string; table: string }[] }> {
    const { plan } = await this.opts.provider.generate(prompt, ctx);
    const endpoints: { method: string; path: string; table: string }[] = [];
    for (const t of plan.database.tables) {
      endpoints.push(
        { method: 'GET', path: `/:projectId/${t.name}`, table: t.name },
        { method: 'POST', path: `/:projectId/${t.name}`, table: t.name },
        { method: 'PATCH', path: `/:projectId/${t.name}/:rowId`, table: t.name },
        { method: 'DELETE', path: `/:projectId/${t.name}/:rowId`, table: t.name },
      );
    }
    return { endpoints };
  }

  async generateAuthDesign(prompt: string, ctx: Record<string, unknown>): Promise<AIPlan['auth']> {
    const { plan } = await this.opts.provider.generate(prompt, ctx);
    return plan.auth;
  }

  async generateStorageDesign(
    prompt: string,
    ctx: Record<string, unknown>,
  ): Promise<AIPlan['storage']> {
    const { plan } = await this.opts.provider.generate(prompt, ctx);
    return plan.storage;
  }

  async generateRealtimeDesign(
    prompt: string,
    ctx: Record<string, unknown>,
  ): Promise<AIPlan['realtime']> {
    const { plan } = await this.opts.provider.generate(prompt, ctx);
    return plan.realtime;
  }

  async generateFunctionsDesign(
    prompt: string,
    ctx: Record<string, unknown>,
  ): Promise<AIPlan['functions']> {
    const { plan } = await this.opts.provider.generate(prompt, ctx);
    return plan.functions;
  }

  validatePlan(plan: AIPlan, existing?: ExistingState): PlanValidation {
    return validatePlan(plan, existing);
  }

  estimate(plan: AIPlan): ReturnType<typeof estimateResources> {
    return estimateResources(plan);
  }

  /** Full pipeline: generate → validate → store → audit. Never executes. */
  async requestPlan(input: {
    projectId: string;
    organizationId: string;
    userId: string;
    prompt: string;
    existing: ExistingState;
    context: Record<string, unknown>;
  }): Promise<StoredPlan> {
    const { plan, usage } = await this.opts.provider.generate(input.prompt, input.context);
    this.opts.usage.trackRequest(input.projectId, usage, true);
    const stored = this.opts.plans.create({
      projectId: input.projectId,
      organizationId: input.organizationId,
      userId: input.userId,
      prompt: input.prompt,
      provider: this.opts.provider.name,
      model: usage.model,
      raw: plan,
      existing: input.existing,
    });
    // Destructive intent usually lives in the raw prompt, not the generated
    // summary — flag it here so approval gates on the user's actual words.
    for (const op of detectDestructiveOps(input.prompt)) {
      if (!stored.validation.destructive.includes(op)) stored.validation.destructive.push(op);
    }
    this.opts.audit.record({
      projectId: input.projectId,
      organizationId: input.organizationId,
      userId: input.userId,
      action: 'AI_PLAN_GENERATED',
      resource: stored.id,
      result: stored.validation.ok ? 'ok' : 'error',
      detail: stored.validation.ok
        ? stored.plan.summary.slice(0, 200)
        : (stored.validation.errors[0] ?? 'invalid'),
      prompt: input.prompt,
    });
    return stored;
  }

  /**
   * Apply an approved plan through project-bound tools. Each step is
   * recorded; the first failure stops the pipeline. If the migration step
   * itself fails midway, best-effort inverse statements run and the outcome
   * reports rolled_back — never a false success.
   */
  async applyPlan(input: {
    projectId: string;
    planId: string;
    adapters: ToolAdapters;
    level: PermissionLevel;
    userId: string;
    organizationId: string;
  }): Promise<ApplyOutcome> {
    const plans = this.opts.plans;
    const plan = plans.markApplying(input.projectId, input.planId);
    const steps: { step: string; ok: boolean; detail: string }[] = [];
    const step = (s: string, ok: boolean, detail: string): void => {
      steps.push({ step: s, ok, detail });
      plans.recordStep(input.projectId, input.planId, s, ok, detail);
    };
    let migration: Migration | null = null;
    let rolledBack = false;
    try {
      // 1. Migration (DDL via validated statements only, tool-permission checked).
      if (plan.plan.database.tables.length > 0) {
        migration = buildMigration(plan.plan, plan.id, input.projectId);
        migration.status = 'approved';
        migration.status = 'executing';
        const mres = (await executeTool(input.adapters, input.level, {
          tool: 'create_migration',
          args: { statements: migration.statements },
        })) as { ok: boolean; result: { executed: number } };
        migration.status = 'executed';
        migration.executedAt = new Date().toISOString();
        step(
          'migration',
          true,
          `executed ${mres.result.executed} statements (${migration.checksum.slice(0, 12)})`,
        );
      } else {
        step('migration', true, 'no database changes');
      }
      // 2. Storage buckets.
      for (const b of plan.plan.storage.buckets) {
        const res = await executeTool(input.adapters, input.level, {
          tool: 'create_bucket',
          args: {
            name: b.name,
            visibility: b.visibility,
            allowedMimeTypes: b.allowedMimeTypes,
            maxFileMb: b.maxFileMb,
          },
        });
        step('bucket', true, JSON.stringify(res.result).slice(0, 200));
      }
      // 3. Functions (scan generated/scaffolded source, then deploy).
      for (const f of plan.plan.functions) {
        const source = f.source ?? scaffoldFunctionSource(f.name, f.purpose, f.trigger, f.table);
        const scan: ScanResult = scanGeneratedCode(source);
        if (!scan.safe) {
          throw new Error(
            `function ${f.name} failed safety scan: ${scan.findings[0]?.rule ?? 'blocked'}`,
          );
        }
        const res = await executeTool(input.adapters, input.level, {
          tool: 'create_function',
          args: { name: f.name, purpose: f.purpose, source },
        });
        step('function', true, JSON.stringify(res.result).slice(0, 200));
      }
      // 4. Realtime channels.
      for (const c of plan.plan.realtime.channels) {
        const res = await executeTool(input.adapters, input.level, {
          tool: 'enable_realtime',
          args: { topic: c.topic, kind: c.kind, table: c.table },
        });
        step('realtime', true, JSON.stringify(res.result).slice(0, 200));
      }
      // 5. Auth policies are recorded, enforced by the existing RLS layer.
      if (plan.plan.auth.policies.length > 0) {
        step('auth', true, `${plan.plan.auth.policies.length} policies recorded for RLS layer`);
      } else {
        step('auth', true, 'no auth changes');
      }
      plans.markFinished(input.projectId, input.planId, true, null, false);
      this.opts.usage.trackApply(input.projectId, true);
      this.opts.audit.record({
        projectId: input.projectId,
        organizationId: input.organizationId,
        userId: input.userId,
        action: 'AI_CHANGE_APPLIED',
        resource: plan.id,
        result: 'ok',
        detail: `${steps.length} steps applied`,
      });
      return {
        plan: plans.get(input.projectId, input.planId),
        migration,
        steps,
        ok: true,
        rolledBack,
        error: null,
      };
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Apply failed';
      step('failed-step', false, message.slice(0, 300));
      // Best-effort rollback: only safe when the migration created tables and
      // nothing else has applied yet beyond it.
      const onlyMigration =
        migration !== null && steps.filter(s => s.ok && s.step !== 'migration').length === 0;
      if (onlyMigration && migration) {
        try {
          await input.adapters.rollbackMigration(migration.rollbackStatements);
          migration.status = 'rolled_back';
          rolledBack = true;
        } catch {
          migration.status = 'failed';
        }
      } else if (migration) {
        migration.status = 'failed';
      }
      plans.markFinished(input.projectId, input.planId, false, message, rolledBack);
      this.opts.usage.trackApply(input.projectId, false);
      this.opts.audit.record({
        projectId: input.projectId,
        organizationId: input.organizationId,
        userId: input.userId,
        action: rolledBack ? 'AI_CHANGE_ROLLED_BACK' : 'AI_CHANGE_FAILED',
        resource: plan.id,
        result: 'error',
        detail: message.slice(0, 300),
      });
      return {
        plan: plans.get(input.projectId, input.planId),
        migration,
        steps,
        ok: false,
        rolledBack,
        error: message.slice(0, 500),
      };
    }
  }

  preview(plan: AIPlan, existing: ExistingState): ChangeLine[] {
    return diffPlan(plan, existing);
  }

  migrationPreview(plan: AIPlan, planId: string, projectId: string): string[] {
    return buildMigration(plan, planId, projectId).statements.map(s => s.slice(0, 500));
  }
}

export function builderFromConfig(
  cfg: AIProviderConfig,
  deps: { plans: PlanStore; audit: AIAuditLog; usage: AIUsageTracker },
): AIBackendBuilder {
  return new AIBackendBuilder({
    provider: providerFromConfig(cfg),
    plans: deps.plans,
    audit: deps.audit,
    usage: deps.usage,
  });
}

export type { Analysis, DestructiveOp };
