import type { DiffSchema } from './diff.js';

/**
 * Generated database types: deterministic TypeScript interfaces from an
 * inspected schema. Powers SDK type-safety (`npx cloudnivo types`) without
 * hand-maintained models. Mapping is conservative — unknown Postgres types
 * become `unknown` rather than a wrong guess.
 */

const PG_TO_TS: [RegExp, string][] = [
  [/^(smallint|integer|bigint|smallserial|serial|bigserial)$/, 'number'],
  [/^(numeric|decimal|real|double precision|money)$/, 'number'],
  [/^(boolean)$/, 'boolean'],
  [/^(text|character varying|character|varchar|char|name|uuid|json|jsonb|xml|inet|cidr|macaddr|interval|bytea)$/, 'string'],
  [/^(date|timestamp|timestamptz|timestamp with time zone|timestamp without time zone|time|timetz)$/, 'string'],
  [/^ARRAY$/, 'unknown[]'],
  [/^\w+$/, 'unknown'],
];

export function pgTypeToTs(pgType: string): string {
  const t = pgType.trim().toLowerCase();
  if (t.endsWith('[]')) return `${pgTypeToTs(t.slice(0, -2))}[]`;
  for (const [re, ts] of PG_TO_TS) {
    if (re.test(t)) return ts;
  }
  return 'unknown';
}

function toPascal(name: string): string {
  return name
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

function toCamel(name: string): string {
  const pascal = toPascal(name);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

function safeProp(name: string): string {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

/** Deterministic, sorted output — byte-stable for codegen diffing. */
export function generateTypescriptTypes(schema: DiffSchema, opts: { schemaPrefix?: boolean } = {}): string {
  const tables = [...schema.tables].sort((a, b) =>
    `${a.schema}.${a.name}`.localeCompare(`${b.schema}.${b.name}`),
  );
  const lines: string[] = [
    '// Generated by CloudNivo — do not edit. Regenerate with `npx cloudnivo types`.',
    '',
  ];
  for (const table of tables) {
    const typeName =
      (opts.schemaPrefix && table.schema !== 'public' ? `${toPascal(table.schema)}` : '') +
      toPascal(table.name);
    lines.push(`export interface ${typeName} {`);
    const cols = [...table.columns].sort((a, b) => a.name.localeCompare(b.name));
    for (const col of cols) {
      const optional = col.nullable && !col.defaultValue ? '?' : '';
      lines.push(`  ${safeProp(toCamel(col.name))}${optional}: ${pgTypeToTs(col.dataType)};`);
    }
    lines.push('}');
    lines.push('');
  }
  lines.push('export interface Database {');
  for (const table of tables) {
    const typeName =
      (opts.schemaPrefix && table.schema !== 'public' ? `${toPascal(table.schema)}` : '') +
      toPascal(table.name);
    lines.push(`  ${safeProp(table.schema === 'public' ? toCamel(table.name) : `${toCamel(table.schema)}_${toCamel(table.name)}`)}: ${typeName};`);
  }
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}
